### ISSUE TITLE
Can't process \hat lable

### ISSUE THREAD

**Issue by flyaway1217** [akfish/hexo-math#22]
![image](https://cloud.githubusercontent.com/assets/1570846/13904233/7692f13c-eed4-11e5-8f72-7bab6fa757ea.png)
the code is :
$\hat{w} = (w^T, b)^T$

**Comment by flyaway1217** [comment]
the code {% math %} \hat{w} = (w^T, b)^T{% endmath %} can parse successfully.

**Comment by akfish** [comment]
![image](https://cloud.githubusercontent.com/assets/922715/13904538/1557e110-eedf-11e5-9c6c-a865ea25e385.png)

I cannot reproduce this issue on my end. Which version are you using? What's the page's HTML looks like?

**Comment by flyaway1217** [comment]
I am using up-to-date version, I just updated....
The HTML code is 
![image](https://cloud.githubusercontent.com/assets/1570846/13904563/f2a4f79c-eedf-11e5-8541-466360d0759e.png)

I have changed all the codes into {% math %} block....it works well !
I did some experiments. I found that if there is a \hat in the post, it's ok, and if there is two or more \hat labels in post, there is an error.
You can try use two \hat labels in the same line, this issue should be reproduced.

**Comment by akfish** [comment]
Still can't reproduce this issue. Though it's seems that it's either a Hexo's issue or MathJax's.

It is expected that inline/block MathJax expression might produce unexpected results, since math equations often have unescaped special characters that can be messed up by Hexo's rendering engine. That's why I added `{% math %}` tag in the first place.

Close for now.
